# Generated by Django 6.0.2 on 2026-04-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='health_score',
            field=models.IntegerField(default=100),
        ),
    ]
