# Generated by Django 6.0.2 on 2026-02-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_image',
            field=models.ImageField(default='user_images/default.jpg', null=True, upload_to='user_images/'),
        ),
    ]
