# Generated by Django 6.0.2 on 2026-04-24 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OverviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomalies', models.JSONField(blank=True, null=True)),
                ('forecasts', models.JSONField(blank=True, null=True)),
                ('total_spent', models.JSONField(blank=True, null=True)),
                ('total_saving', models.JSONField(blank=True, null=True)),
                ('health_score', models.JSONField(blank=True, null=True)),
                ('budget_count_list', models.JSONField(blank=True, null=True)),
                ('warnings', models.JSONField(blank=True, null=True)),
                ('tips', models.JSONField(blank=True, null=True)),
                ('spend_trend', models.JSONField(blank=True, null=True)),
                ('is_refreshed', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('prediction_count', models.IntegerField(blank=True, null=True)),
                ('data_points', models.FloatField(blank=True, default=0, null=True)),
                ('accuracy_percentage', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_overview', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_sharelink', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnomalyState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=100)),
                ('is_true', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'reference_id'), name='unique_state_per_user')],
            },
        ),
    ]
