# Generated by Django 6.0.2 on 2026-04-20 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OverviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomalies', models.JSONField(blank=True, null=True)),
                ('total_spent', models.JSONField(blank=True, null=True)),
                ('total_saving', models.JSONField(blank=True, null=True)),
                ('health_score', models.JSONField(blank=True, null=True)),
                ('budget_count_list', models.JSONField(blank=True, null=True)),
                ('warnings', models.JSONField(blank=True, null=True)),
                ('tips', models.JSONField(blank=True, null=True)),
                ('spend_trend', models.JSONField(blank=True, null=True)),
                ('is_refreshed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_overview', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ShareLink',
        ),
    ]
