# Generated by Django 6.0.2 on 2026-04-24 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anomalystate',
            old_name='is_true',
            new_name='mark_safe',
        ),
    ]
