# Generated by Django 6.0.2 on 2026-04-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_overviewmodel_delete_sharelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='overviewmodel',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
