# Generated by Django 6.0.2 on 2026-04-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_sharelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='overviewmodel',
            name='accuracy_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='overviewmodel',
            name='prediction_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
