# Generated by Django 6.0.2 on 2026-04-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_overviewmodel_accuracy_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overviewmodel',
            name='accuracy_percentage',
        ),
    ]
