# Generated by Django 6.0.2 on 2026-04-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_remove_overviewmodel_accuracy_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='overviewmodel',
            name='accuracy_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
