# Generated by Django 6.0.2 on 2026-04-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_overviewmodel_accuracy_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='overviewmodel',
            name='forecasts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
