# Generated by Django 6.0.2 on 2026-04-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0008_overviewmodel_forecasts'),
    ]

    operations = [
        migrations.AddField(
            model_name='overviewmodel',
            name='data_points',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
