# Generated by Django 6.0.2 on 2026-02-09 07:52

import django.core.validators
import django.db.models.deletion
import expense.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_name', models.CharField(blank=True, max_length=100, null=True)),
                ('budget_limit', models.CharField(choices=[('MONTHLY', 'Monthly Budget'), ('WEEKLY', 'Weekly Budget'), ('YEARLY', 'Yeatly Budget'), ('SEMI YEARLY', 'Semi Yearly Budget'), ('DAY', 'Day Budget')], max_length=200)),
                ('budget_field', models.CharField(choices=[('FOOD', 'Food Expense'), ('PERSONAL', 'Personal Expense'), ('TRIP', 'Trip Expense'), ('CLOTHS', 'Cloths Expense'), ('OTHERS', 'Others'), ('GROCERY', 'Grocery Expenses')], max_length=200)),
                ('active_budget', models.BooleanField(default=False)),
                ('budget_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10000000.0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_budgets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(max_length=250)),
                ('expense_description', models.TextField()),
                ('expense_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('expense_category', models.CharField(choices=[('FOOD', 'Food Expense'), ('PERSONAL', 'Personal Expense'), ('TRIP', 'Trip Expense'), ('CLOTHS', 'Cloths Expense'), ('OTHERS', 'Others'), ('GROCERY', 'Grocery Expenses')], max_length=50)),
                ('expense_image', models.ImageField(blank=True, null=True, upload_to=expense.models.upload_user_expense_image)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budgets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_expenses', to='expense.budget')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
