# Generated by Django 6.0.2 on 2026-03-20 07:15

import cloudinary.models
import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('id', models.CharField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('budget_name', models.CharField(blank=True, max_length=100, null=True)),
                ('budget_limit', models.CharField(choices=[('MONTHLY', 'Monthly Budget'), ('WEEKLY', 'Weekly Budget'), ('YEARLY', 'Yearly Budget'), ('SEMI YEARLY', 'Semi Yearly Budget'), ('DAY', 'Day Budget')], max_length=200)),
                ('budget_field', models.CharField(choices=[('FOOD', 'Food Expense'), ('PERSONAL', 'Personal Expense'), ('TRIP', 'Trip Expense'), ('CLOTHS', 'Cloths Expense'), ('OTHERS', 'Others'), ('GROCERY', 'Grocery Expenses'), ('STUDY', 'Study Expenses')], max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('budget_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10000000.0)])),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_budgets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('expense_name', models.CharField(max_length=250)),
                ('expense_description', models.TextField()),
                ('expense_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('DECLINED', 'Declined'), ('REIMBRUSHED', 'Reimbrushed')], max_length=50)),
                ('expense_category', models.CharField(choices=[('FOOD', 'Food Expense'), ('PERSONAL', 'Personal Expense'), ('TRIP', 'Trip Expense'), ('CLOTHS', 'Cloths Expense'), ('OTHERS', 'Others'), ('GROCERY', 'Grocery Expenses'), ('STUDY', 'Study Expenses')], max_length=50)),
                ('expense_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2026, 3, 20, 7, 15, 36, 300955, tzinfo=datetime.timezone.utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2026, 3, 20, 7, 15, 36, 300968, tzinfo=datetime.timezone.utc))),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_expenses', to='expense.budget')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
