# Generated by Django 6.0.2 on 2026-02-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='active_budget',
            field=models.BooleanField(default=True),
        ),
    ]
