# Generated by Django 6.0.2 on 2026-02-09 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_budget_active_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='budgets',
            new_name='budget',
        ),
    ]
