# Generated by Django 6.0.2 on 2026-03-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_expense_created_at_alter_expense_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
