# Generated by Django 6.0.2 on 2026-02-09 08:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_rename_budgets_expense_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='id',
            field=models.CharField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
