# Generated by Django 6.0.2 on 2026-02-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_budget_created_at_budget_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_limit',
            field=models.CharField(choices=[('MONTHLY', 'Monthly Budget'), ('WEEKLY', 'Weekly Budget'), ('YEARLY', 'Yearly Budget'), ('SEMI YEARLY', 'Semi Yearly Budget'), ('DAY', 'Day Budget')], max_length=200),
        ),
    ]
