# Generated by Django 6.0.2 on 2026-02-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0007_alter_budget_budget_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DECLINED', 'Declined'), ('REIMBRUSHED', 'Reimbrushed')], default=2, max_length=50),
            preserve_default=False,
        ),
    ]
