# Generated by Django 6.0.2 on 2026-02-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0009_alter_expense_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PERSONAL', 'Personal'), ('DECLINED', 'Declined'), ('REIMBRUSHED', 'Reimbrushed')], max_length=50),
        ),
    ]
