# Generated by Django 6.0.2 on 2026-02-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0010_alter_expense_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
