# Generated by Django 6.0.2 on 2026-02-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0011_alter_expense_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PERSONAL', 'Personal'), ('DECLINED', 'Declined'), ('REIMBRUSHED', 'Reimbrushed')], max_length=50),
        ),
    ]
