# Generated by Django 6.0.2 on 2026-02-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0012_alter_expense_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('DECLINED', 'Declined'), ('REIMBRUSHED', 'Reimbrushed')], max_length=50),
        ),
    ]
