# Generated by Django 6.0.2 on 2026-02-27 06:46

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0013_alter_expense_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 27, 6, 46, 11, 22424, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 27, 6, 46, 11, 22446, tzinfo=datetime.timezone.utc)),
        ),
    ]
