# Generated by Django 6.0.2 on 2026-02-27 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0014_alter_expense_created_at_alter_expense_expense_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_field',
            field=models.CharField(choices=[('FOOD', 'Food Expense'), ('PERSONAL', 'Personal Expense'), ('TRIP', 'Trip Expense'), ('CLOTHS', 'Cloths Expense'), ('OTHERS', 'Others'), ('GROCERY', 'Grocery Expenses'), ('STUDY', 'Study Expenses')], max_length=200),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 27, 8, 27, 45, 349315, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_category',
            field=models.CharField(choices=[('FOOD', 'Food Expense'), ('PERSONAL', 'Personal Expense'), ('TRIP', 'Trip Expense'), ('CLOTHS', 'Cloths Expense'), ('OTHERS', 'Others'), ('GROCERY', 'Grocery Expenses'), ('STUDY', 'Study Expenses')], max_length=50),
        ),
        migrations.AlterField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 27, 8, 27, 45, 349333, tzinfo=datetime.timezone.utc)),
        ),
    ]
