# Generated by Django 6.0.2 on 2026-02-27 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0015_alter_budget_budget_field_alter_expense_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='active_budget',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='budget',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 27, 10, 12, 44, 592504, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 27, 10, 12, 44, 592521, tzinfo=datetime.timezone.utc)),
        ),
    ]
