# Generated by Django 6.0.2 on 2026-02-27 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0016_rename_active_budget_budget_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 27, 10, 24, 23, 863033, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 27, 10, 24, 23, 863052, tzinfo=datetime.timezone.utc)),
        ),
    ]
